from __future__ import annotations

from .models import MaintainerBrief, IssuePriority


class ReportGenerator:
    """Render MaintainerBrief as Markdown."""

    def generate_markdown(self, brief: MaintainerBrief, repo_name: str) -> str:
        lines = [
            f"# Maintainer Brief - {brief.period}",
            "",
            f"Repository: `{repo_name}`",
            f"Generated at: `{brief.generated_at.strftime('%Y-%m-%d %H:%M UTC')}`",
            "",
            "## Overview",
            "",
            brief.summary,
            "",
            f"- Open issues reviewed: {brief.new_issues_count}",
            f"- Duplicate clusters found: {len(brief.issue_clusters)}",
            f"- Quick wins found: {len(brief.quick_wins)}",
            "",
            "## Top Priorities",
            "",
        ]

        if brief.top_priorities:
            for index, item in enumerate(brief.top_priorities, 1):
                lines.extend(self._priority_lines(index, item))
        else:
            lines.append("No high-confidence priorities were identified.")
            lines.append("")

        if brief.quick_wins:
            lines.extend(["## Quick Wins", ""])
            for item in brief.quick_wins:
                lines.append(f"- #{item.issue_number}: {item.title} ({item.priority_score:.1f}/10)")
            lines.append("")

        if brief.issue_clusters:
            lines.extend(["## Possible Duplicate Clusters", ""])
            for cluster in brief.issue_clusters:
                issue_links = ", ".join(f"#{number}" for number in cluster.issue_numbers)
                lines.extend(
                    [
                        f"### {cluster.cluster_name}",
                        "",
                        f"Issues: {issue_links}",
                        "",
                        cluster.common_theme,
                        "",
                    ]
                )

        if brief.missing_info_issues:
            lines.extend(["## Missing Information", ""])
            for number in brief.missing_info_issues[:10]:
                lines.append(f"- #{number}")
            lines.append("")

        lines.extend(
            [
                "## Trend",
                "",
                brief.trend,
                "",
                "---",
                "",
                "Generated by GitHub Engineer. Recommendations are advisory; maintainers make the final decision.",
                "",
            ]
        )
        return "\n".join(lines)

    @staticmethod
    def _priority_lines(index: int, item: IssuePriority) -> list[str]:
        return [
            f"### {index}. #{item.issue_number}: {item.title}",
            "",
            f"- Score: {item.priority_score:.1f}/10",
            f"- Reason: {item.reason}",
            f"- User impact: {item.user_impact}",
            f"- Estimated effort: {item.estimated_effort}",
            "",
        ]

